version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80" # Map Nginx port 80 to host port 8080
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Map Flask port 5000 to host port 5000
