backend:
  name: ecommerce-backend
  image:
    repository: 017820683847.dkr.ecr.us-east-1.amazonaws.com/ecommerce-app
    # tag will be set dynamically by the pipeline
  replicas: 2
  service:
    type: LoadBalancer
    port: 5000
  resources:
    limits:
      cpu: 800m          # Reserve less than 1 full CPU core per pod
      memory: 1Gi        # Allocate 1 GiB of memory
    requests:
      cpu: 400m          # Minimum CPU request per pod
      memory: 512Mi      # Minimum memory request per pod
  enabled: true          # Added to control backend deployment

mysql:
  name: ecommerce-db
  image:
    repository: mysql
    tag: "8.0"
  service:
    port: 3306
  storage:
    size: 10Gi
    storageClassName: ebs-sc  # Ensures dynamic provisioning using the correct StorageClass
  resources:
    limits:
      cpu: 1000m         # Reserve 1 full CPU core
      memory: 2Gi        # Allocate 2 GiB of memory
    requests:
      cpu: 500m          # Minimum CPU request for stable performance
      memory: 1Gi        # Minimum memory request
  enabled: true          # Added to control MySQL deployment

config:
  flaskDebug: "true"
  sessionType: "filesystem"
  sessionFileDir: "/tmp/flask_sessions"

secrets:
  mysqlRootPassword: admin@1234
  mysqlUser: subbu
  mysqlPassword: admin@1234
  mysqlDatabase: ecommerce
  flaskSecretKey: "ecommerce_app_secret_key_2024_secure_shopping"