apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
data:
  DB_USER: {{ .Values.secrets.mysqlUser | b64enc }}
  DB_PASSWORD: {{ .Values.secrets.mysqlPassword | b64enc }}
  DB_NAME: {{ .Values.secrets.mysqlDatabase | b64enc }}
  SECRET_KEY: {{ .Values.secrets.flaskSecretKey | b64enc }}