apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.flaskSecretKey | b64enc }}
  MYSQL_PASSWORD: {{ .Values.secrets.mysqlPassword | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.secrets.mysqlRootPassword | b64enc }}