version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecom_user
      MYSQL_PASSWORD: ecom_password
    ports:
      - "3306:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
