apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
data:
  FLASK_APP: "app.py"
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5000"
  FLASK_DEBUG: {{ .Values.config.flaskDebug | quote }}
  SESSION_TYPE: {{ .Values.config.sessionType | quote }}
  SESSION_FILE_DIR: {{ .Values.config.sessionFileDir | quote }}