apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: {{ .Release.Name }}-mysql
 labels:
   app: {{ .Values.mysql.name }}
   release: {{ .Release.Name }}
spec:
 replicas: 1
 selector:
   matchLabels:
     app: {{ .Values.mysql.name }}
 serviceName: {{ .Release.Name }}-mysql
 template:
   metadata:
     labels:
       app: {{ .Values.mysql.name }}
       release: {{ .Release.Name }}
   spec:
     containers:
       - name: mysql
         image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
         ports:
           - containerPort: 3306
         envFrom:
           - secretRef:
               name: {{ .Release.Name }}-mysql-secret
         volumeMounts:
           - name: mysql-persistent-storage
             mountPath: /var/lib/mysql
         readinessProbe:
           exec:
             command: ["mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
           initialDelaySeconds: 30
           periodSeconds: 10
         livenessProbe:
           exec:
             command: ["mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
           initialDelaySeconds: 60
           periodSeconds: 20
         startupProbe:
           exec:
             command: ["mysqladmin", "ping", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
           failureThreshold: 30
           periodSeconds: 10
         lifecycle:
           postStart:
             exec:
               command:
                 - bash
                 - -c
                 - |
                   mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
                   mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';"
         resources:
           {{- toYaml .Values.mysql.resources | nindent 12 }}
 volumeClaimTemplates:
   - metadata:
       name: mysql-persistent-storage
     spec:
       accessModes:
         - ReadWriteOnce 
       storageClassName: {{ .Values.mysql.storageClassName }}
       resources:
         requests:
           storage: {{ .Values.mysql.storage.size }}