apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: {{ .Values.mysql.name }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  serviceName: {{ .Release.Name }}-mysql-service
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-mysql-secret
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mysql.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-persistent-storage
        labels:
          app: {{ .Values.mysql.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mysql.storage.size }}
        {{- if .Values.mysql.storageClassName }}
        storageClassName: {{ .Values.mysql.storageClassName }}
        {{- end }}
